######################################################################
# Automatically generated by qmake (2.01a) Sat Jan 26 16:45:45 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DAQSettingsDialog.h
FORMS += DAQSettingsDialog.ui
SOURCES += DAQSettingsDialog.cpp main.cpp
